---
title: "Introduction to fieldClim"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to fieldClim}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction to the Package

The `fieldClim` package was originally designed as a course project to the course `Geländeklimatologie`, held by Prof. Dr. Jörg Bendix at the Philipps-University of Marburg. Thus, the calculations and formulas of this package are based on this course, as well as on the books `Geländeklimatologie` (Field Climatology) by Jörg Bendix (2004; ISBN 978-3-443-07139-4) and `Angewandte Meteorologie` (Applied Meteorology) by Thomas Foken (2016, ISBN 978-3-642-25524-3).
The package was first developed by David Langenohl and Jonas Viehweger in summer semester 2020 (https://github.com/jonasViehweger/fieldClim/) and later by Fabian Mitze and Hanna Wenzel in summer semester 2021 (https://github.com/FabianMitze/fieldClim).
This version by Kai Richter and You-De Chen in summer semester 2023 (https://gitlab.uni-marburg.de/fb19/ag-bendix/fieldClim) is a revision of the Mitze & Wenzel version with profound structural changes and bug fixes. The revision was mainly focused on heat balance equations in chapter 1 to 4, but also several further functions used in the course.

`fieldClim` is designed as a handy tool for calculations of various weather and micro-climate conditions based on the measurements of a weather station.
Almost for each function, there are two methods to use: “Default S3 method” and “S3 method for class 'weather_station'”. Take the function rad_bal for example (?rad_bal). You need to give as input all the listed arguments for the default method to work. The inputs can be a single value or a vector. If you plan to use multiple functions from this package, the weather_station method can save you time. You need to create a list of arguments using function build_weather_station and then give this list as an input to other functions. See "Check-rad-and-soil.html" and "Check_lat_sens_turb_heat_flux.html" for more detailed usage examples.


**References**

Bendix, J. (2004): Geländeklimatologie. 1st edition. (ISBN 978-3-443-07139-4)

Foken, T. (2016): Angewandte Meteorologie: Mikrometeorologische Methoden. 3rd edition. (ISBN 978-3-642-25524-3)

Lente, G. & K. Ősz (2020): Barometric formulas: various derivations and comparisons to environmentally relevant observations. ChemTexts (2020) 6:13. <https://doi.org/10.1007/s40828-020-0111-6>
